# 서버 포트 설정
server:
  port: 8787

spring:
  # Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicelog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gateway
    password: gateway12
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      use-new-id-generator-mappings: false
  #kafka 연동
  cloud:
    bus:
      enabled: true
  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: gateway
    password: gateway