# 서버 포트 설정
server:
  port: 7777


spring:
  #cache(Redis) 설정
  cache:
    type: redis
  redis: 
    host: localhost
    port: 6379
  # Datasource 설정    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true

# 로그 설정
logging:
  config: classpath:${spring.profiles.active}/log4j2.yml
#  level:
#    org:
#      hibernate:
#        SQL: INFO
#        type:
##          descriptor:
#            sql:
#              BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: auth-service             